import { Layout } from 'components/layout/layout'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import TelegramProvider from 'providers/TelegramProvider'

import './globals.css'

const Gotham = localFont({
	src: [
		{
			path: '../fonts/Gotham-Book.woff2',
			weight: '400',
			style: 'normal'
		},
		{
			path: '../fonts/Gotham-Medium.woff2',
			weight: '500',
			style: 'normal'
		},
		{
			path: '../fonts/Gotham-Bold.woff2',
			weight: '700',
			style: 'normal'
		}
	]
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${Gotham.className} antialiased`}>
				<TelegramProvider>
					<Layout>{children}</Layout>
				</TelegramProvider>

				<script src='https://telegram.org/js/telegram-web-app.js?58'></script>
			</body>
		</html>
	)
}
